import { Inter, Roboto_Mono } from "next/font/google";
import '../styles/globals.scss';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});
 
export const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>{children}</body>
    </html>
  );
}
